---
- hosts: all
  sudo: true
  vars:
    servername: myApp.vb www.myApp.vb 192.168.33.40
    timezone: Asia/Tokyo
  vars_files:
    - vars/common.yml
  roles:
    - init
    - apache
    - php
    - mysql
    - composer
